### ISSUE TITLE
On clicking User image in residents detail, User should be able to view user image. 

### ISSUE THREAD

**Issue by puneet739** [puneet739/SocietyFocus-Android#12]

**Comment by SagarKhurana** [comment]
Completed.

**Comment by puneet739** [comment]
@SagarKhurana  @laherajmani  On residents detail page, there is white header and same with image activity. We need to fix that. After that this issue is closed.

**Comment by SagarKhurana** [comment]
@puneet739  I think that is the status bar u are seeing... on some pages that is black... on other it is blue ...and on some it is transparent/white... please let me know how we should go with this...

**Comment by puneet739** [comment]
@SagarKhurana we should have default black in all the pages.. The same as we are using in home page.

**Comment by puneet739** [comment]
@SagarKhurana Fixed and closing
