### ISSUE TITLE
User Detail page, Remove magnet. 

### ISSUE THREAD

**Issue by puneet739** [puneet739/SocietyFocus-Android#13]

**Comment by SagarKhurana** [comment]
@puneet739  can you proivde some more information about magnet?

**Comment by puneet739** [comment]
@SagarKhurana Regarding the user detail page, there is a magnet kind of feature, which is
pulling the screens either to top of screen or at same point.
Altough in GMail app it is stooping at exact point where you leave.. kindly
check this once.

**Comment by puneet739** [comment]
@SagarKhurana  need to discuss this.

**Comment by puneet739** [comment]
@SagarKhurana issue still exists.

**Comment by SagarKhurana** [comment]
@puneet739 i am unable to understand the feature required in this issue... can you provide some more details about it!

**Comment by puneet739** [comment]
Fixed.. Need not work on this.
