### ISSUE TITLE
On User Detail Page --> No Phone no present dont call 6855

### ISSUE THREAD

**Issue by puneet739** [puneet739/SocietyFocus-Android#2]
If user have not provided any phone no, when you call user it dials 6855. 

Expected Result:: 
It should be saving, no number provided.

**Comment by SagarKhurana** [comment]
Completed.

**Comment by puneet739** [comment]
@SagarKhurana have you committed and pushed the code?

**Comment by SagarKhurana** [comment]
yes.

**Comment by puneet739** [comment]
Hi @SagarKhurana 

Kindly create a pull request from your updated fork so that I can merge the latest code and create a release

**Comment by puneet739** [comment]
Fixed and Closed
