### ISSUE TITLE
Settings layout need beautification.

### ISSUE THREAD

**Issue by puneet739** [puneet739/SocietyFocus-Android#4]
Settings layout need beautification.

**Comment by puneet739** [comment]
![img-20160724-wa0008](https://cloud.githubusercontent.com/assets/4660008/17082731/0ce25f54-51a6-11e6-8e59-a7a039677cf9.jpg)

**Comment by SagarKhurana** [comment]
@puneet739  the above image is for the reference of the edit user profile or Settings layout?

What all features we would be including in settings layout like change password.. !!
please share your views about it.

**Comment by puneet739** [comment]
@SagarKhurana 
Yes, Apart from above view there can be one more option of change password.. 
1) Name
2) address
3) Description/about yourself
4) Occupation
5) Phone no

6) Change picture.

**Comment by puneet739** [comment]
In order to upload Image 
http://societyfocus.com/service/upload/image

Post
Form-Data

```
POST /service/upload/image HTTP/1.1
Host: societyfocus.com
Cache-Control: no-cache
Postman-Token: 5926d889-adeb-9a8e-34a0-af96b33735ce
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="filenews"; filename=""
Content-Type: 


------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

Refrence can be found in postman collection shared with you.

**Comment by puneet739** [comment]
@SagarKhurana 
For Cropped images 

Post Message
http://societyfocus.com/service/upload/image/base64

This will accept base64 encoded images. 

``` json
{
"base64":{base64string},
"filename":{filename of original file}
}
```

**Comment by SagarKhurana** [comment]
@puneet739  I am able to get the image from gallery/ camera to our app... but now ... 
if i will call "/service/upload/image" API as post request sending the imagebytes in json... what response I will get? I could not find it in the json Collections.

and what is the difference in cropped pics and others?

and after uploading the image how i am suppose to update the url of user's object as profile pic, or this you are handling at back-end.

**Comment by puneet739** [comment]
Hi @SagarKhurana 
Please find the answer inline

I am able to get the image from gallery/ camera to our app... but now ... 
if i will call "/service/upload/image" API as post request sending the imagebytes in json... what response I will get? I could not find it in the json Collections.
Puneet: In reponse you will get the image url on which the image is uploaded. 

and what is the difference in cropped pics and others?
Puneet: If you will crop an image you will end up with base64 encoded image data. Which need to be sent in different format. If you have that as .jpg you can you other api as well. 

and after uploading the image how i am suppose to update the url of user's object as profile pic, or this you are handling at back-end.
Puneet: After uploading the image, you need to call the update user with profile_pic param as the new uploaded image url

**Comment by SagarKhurana** [comment]
@puneet739  what are we sending in ImageBytes as input...
 I sent ByteArray and got 415 unsupported Media type

**Comment by puneet739** [comment]
Post JSON request. 

``` json
{
POST /zircon/services/upload/image/base64 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 14dc0667-c20c-ac11-f9ce-574715979de7

{
"base64":"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/4QAiRXhpZgAATU0AKgAAAAgAAQESAAMAAAABAAEAAAAAAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAAhAQ0DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9zAM1BqupW+iaZcX15PHbWdnG0800hwsSKNxY+wAzU5OFY+gJ+tfNf/BYLxPqHhH/AIJxfFa603zPtDaQbctGxVold0VmBHoCf5+1AHi+gftq/tDf8FC/FGsXH7Oej+E/Bvw30m4a1j8U+MYZJG1mVc7jDDGrnZwSOuBhiRyBJB+3h8dv2F/jB4T8P/tK6P4X1nwb40vE0zTvGnhh2W2s7pj8kdzG4UjPU/L8q5POK+hv+CZvhLSfB/8AwT3+Ddno8cMdnceENPvS6qFWaSe3immcjvuldyQe7kZAOB6L8Z/hz4J+JXhCSx8e6P4d1TQ/NWYxazDE1usg4Rvm4yOQD1wKAPFPi3+194j8D/8ABTD4R/COzt9PPhfx9oGoapeyyQYufMghndApzwN0Q49PrX0t50ZnZN6/u22uM5ZenYZ9a/NL/gpV8OPEHxS/4LA/s/8Ahrwj4iuvCV7rnhfU7aTVrPatxZ2bLO8/lnAVWNvvRTg4LA9qyv24f2Tbb/gllH8O/iv8LfG3xCivV8VWWm61Z6xrsl9DrdvM5DiRG4DsARuA5DdBigD9ROi8g7hwVHPTr7en1GfSmpIsxPksJgr7CycgNk8H8Bmvk7/gpB8HfFXxn8X+CtL1T4lWfwr+CUDSz+LLyLWYtIv7+cbhDbo8hwI8MucHjOeSMH4h8ZeLvhD+x/8Atl/Alf2c/i94m8SXPiHxbY6H4n0x9dk1awurGeaKFmaRl2eZ+8IGwk5IOMDFAH7IbgVyGDZUuAOu31/nSq6yGQKdxjYg4IPp6Hr3Ppivzb/bQ8PeOPjN/wAFkvC/w78O+Nta8I+H/EXgj/icSafcMrR2yyytKYxu2rI/lrHvwcBicZrJ/aa/Zlh/4JYfHP4I+NPhf4w8c/Y/EnjC28O+INL1rWZNQttTgmcZZt/R9pJ3ADsccYIB+nLME+8yrjrk4+n5+hxQDvUMo3Kx2hs8MRgEA9OpA5x39K+Av2rb/wASft+f8FG5/wBnez8Va94R+G/gXQI/EHis6NOLW+1aaUoY4vNwdihZo14B7ntXiP8AwVC/Y91j/gn38NfBt98M/iD46i8E+JfFenaXrGk6jqzXJiuMs0MsMmA6IwEodTuG4rzQB+tg+c/Lhhu2gjv36deO/YHvTfPRk3Kylc9dw4yCQOvXg5Havzv/AOCpP7Xlpf8A7X3g74E618TJPhL4FuNE/t/xdrcFyLa6vEMkiRWEMgBaMnyySRkkPnjHPhPxL+OHwe/4J+eNvCvxA/Z5+OmoeJsatBpvifwfqetTapFqljKWWSZVlX5JUIzkHtn2IB+xTLscg/LhivzdR6H+v4V8O/t5ftnfGzwH+3h4B+C/wjg8GSXPi7w9JqnmeIVcRxyLLNn50BP+rhwMA5JA4619raJqcWsaVbXVv80F3DHPGW4Yo43LwcHoe2cV+ZX/AAUl+M0/wD/4LW/BbxRZ+FvEnjWax8FThNK0K1N1fzhpLxD5aAEnbu3HjhVY9qAPRfiJ8YP27fgB4Pv/ABXrXg74PeMtF0WJrvUdP0S7n+2LbJkyECSNPmCBiMZ6V9VfsZftUaL+2n+zn4b+IWgw3FnZ65E4e0ly8lnLG5SSInHIDA88V8m/Fr/gqT8Ufit8OdW8O+Bv2W/jTa+ItatHs7a61zRWtbG1aUNH5krumNqhi2NwzjHetr4N/sV/Fr9lb/gklZfDHwVrukaD8TJt09/qdzcFYdMFxL5lz5cmCoKIxAYgctn5cZoA+5xIpk2bgJNu4oxAZR6kdce/SlwT0U4PQkYBHr+Ffjf+2F8HP2b/ANmv9nvXta8M/tFeLNZ+Nmh2y3dneWfjA6lNdagowyyxRAoiMc53H5VJOTjB9U/bs/aW+JPij/gm7+z/AOJ5NQ8U6f4X8YNYyfEbWNARjf21m8aBiWUfuwxON3Q9BknFAH6dRyLKG2tuaM7XAOdpH3unYcdcHnoKWSRYomdmG1QTn1xnv+Fflz8JPgH8Kdf8Z+EfEf7JP7Qt3beMLLUYpdT0XX/FMtw2sWOCZUe1mIfzOM/KNvHQYzWn/wAFbPiM0H7d3gPw78Xde8ceD/2eb7QTcNe+H5JbeC71Qyybo55YwWCALEMAd89M0AfpmHDn5ecnA5DZPGOVJHf1pd28/J82TgfX8M+3518CfsM/APw74L/af0vxB+zz8cLXxl8Jbyxmh8T+Fr/xJ/acsBbmOaFD+8jIJUndjOCK0/2C/F2rfAP9vn9oz4R+INU1G901ZovGnh031w00kdjOhLpGWI+RC+36xnpQB90MQC3X5Ruxj5sdsgZwT6GhyEbk/rz3GcdcZGM1+V3/AAS2+O3jB/2/7jxB4n1rULrwn+0VY6zqHhy3lmdobdrG+Pl7FJwMw5PGP9YvWvSfg78dtQm/aQ/a5+Pl5fXt54S+F8Fz4Z0Sy+0M1o72KM9wyKTtYtLEwDY53gUAfoOzrHjeyrzt+8OT6D145pSQN3qv8II3D3Iz0r83f2Pv+Cf97/wUM+CVl8Zvjf8AED4iX3iLx4H1PTNP0fW302y0K0YkQrHGgG5wuMk9DxjvXRfsPfFnx18FPj98aP2bfG/ijUvGUfgvQH1/wrrV4Qb57F1C+XI4GWZDIoBJzk54oA+/5HWNHYtGqx9WZgqjjI5Pr9OnJx2WV1gdt/yrHy24YIHJHB9geQce9fkj/wAExP2TfG//AAUU+AWm6p8Rfib4z0nwD4L129tdI0rSr7y5tVnW7kuJbi4lkDs20yGEKcjYgwQcY9K8LeB9a/4K5/tl/Fm18WeLvFOi/CH4SaqfDun6Fod/9gOp3ik+dJMyAbgNvTBJ343DHIB9H/t5/td+Jv2afjD8A/D+hQ6fcWfxQ8a2/h3VHuITI0du7orGNuADh8cZ+tfSgOGbHAYgn3xuH54x+Vfkj+11+xzqv7HP7b37K+k6P4w8UeIPhnqXxF0+aw03XrsXk2i3ouIA6xSkBvLdTnaemOpr9b9uCfw/rQAUUUUAArkfj78G9L/aH+C3ibwPrSsdN8T6dNp9wQcEb1IDA9iDg59q66gjI9u49R3B9j0oA/ND9lL9s/xZ/wAEqvCMfwX+PfgvxZe6P4WZ4PDfjHQtOk1GzvLJmLRxybBuTHO373AAONuTF+0f8UPE/wDwWs8ReGvhh4A8FeLvDvwkstVt9T8WeKNfsjYJdxRHKW8Eb/Mx6/N3LDgYzX6XXljHqCMs8cUytnO9A3XjI9Mjrj0HTvJDCsCKsaxxqpHCIB06f/roA+Ifj54Fv1/4LZfs76hYaRfNoWn+D9Zt2vI7Ui2tibW6WNXYAIpOVGD/ADqx/wAF5PB+reMv2T/Dtto+mahq1wvjPTJZI7K2eZiiucyNtBwi+vvntX2wFHp0zg9/XmgKvcZDDafmP3cAYAzgd+3egD81/wDgpvYQeCv+Ckvw78afFnwZ4k8dfAmz0SS3gtdNsH1G1sNRLNmWW3GQ7cnAb264ryr9uv8AaAs/i1e/B7xH8Nfgn4s8PfCz4a+OtM1vWtUj8MDTnuWSWNtsFogEjKETJZgoLcAZ5r9e5k+0ptlAkDHLA9Cck5AGOeevPSh4UkXYyjyuyYBAPTjI4GM9MH3oA+FBbX3jL/gtz4F8YWej6tH4b1D4Wu8d3PZPGiNK8jrC7EYWQAjKk5Gelan/AAWk8Kav4ssvgT/ZumalqhsviTp1xOttbPMIEVlBaTap2qc4zX2yeRgfLxt47juDn8Oev1oBPnbuOo7np7849ulAHwH+1P4Y8ZfsM/8ABSF/2h9F8Ia9458A+ONBi8P+LLTRoPO1DTpIwvlzLF1kQrDEeMHIkHoT8+f8FZf2ytf/AGxvhz4Bj8M+AfGnhv4c6F4x06S61XxHYf2fNql9I8iQW8MTEu21BMz5xnAPFfcn7W/wK+OB+OOgfET4M+NLNJdP09tN1Xwb4gu510TVFLlhKiqSkcvKjcF/5Zp05z5zd/sffHX9s341+B9Y+O9x4H8L+Bvh/qaa3b+FvDFzJdNqN8gPlvPK6qQFOD0ORkcZoAwv+CjvwIuvhP8AtreDP2g3+Gq/FPwZb6AfDni3Q00yLUJ7SNZJGjvI4XDb3xI47YVDzzxyviD9oLwT+0z4n8N+Df2ef2ddH/ty81GL+29Z8RfDuCy0/RLFMmTJkj+aXlQMHk+meP0oQ7ccJkADABC8Z7Z96jit0gTCLtycsM/Kxwe3+elABY2/2O0jt1WMGNdiLGixxjHG1QBgLngDsOK+EP2i/B2sal/wXe+B+tWuk6nNo1p4Mu4576O1c2sMg+2HY8mNqt868E85r7ykXeG7bht+g9vfPOae75bKjHOeef8APH+NAAZOcg/Kh3gn1Gc/h7V8V/8ABdHwD4x8ffsc6db+F9H1jWtJ0/X7O58UaZpWftN/pKg+bEoH3udnGO2eK+0Qv3c9v8c0qttfdhSRn15Pvzz249qAPyx+Mv7R/wAPfir+x34u+H/7Ov7P/idfEWteG7mwmnbwiNLj0WBoGFy0lwy7nkEe5UVSS77QSASK6r4JftYfEr4Wf8E6fglr3gnwNq/iHwz4KI8O/EDQ7nSGGomOOFBJLAjY3qpY52jByRjvX6RRQJBGqIiiNTwvb246dz25pYY1gChVXamQq9lB6gDtnHPrQB+Pn7bGvfCP9ufQtH0v4B/Bnxjp/wAaJtXtJrLWYPC76OuiMJVaZrlzhWwAVGB1YHPFfWH7T37UHjz9lD4taBp/xC8C33xD+BureG4La/vNK0c6peafqiAJMbhCSXjOFOcd+nGa+0YbaO3LbI0XcCDgYPJB4PXPbNOZFlOJB5iEjKnoQABj05Ax0oA/J/wx4M8HftK/8FFfhD4q/Zr+GvijwPY+F9QlvPGmutosuj6ZPZ4jAiWNwAx++DtHO7Feh/8ABbDwZ4z+E3xN8LfFv4d6LqmtaxrfhzVvAWpCwtpJpES7t2FtK20ceXIVf8+RX6NRWqW8e2NVj+UgbUACnA5Ax7Hj3qYtk9+SSw3HBJPXGcZxxQB+cf7dPwI8QfsnfsWfs8eL/BOi6hq3ib4F3dsPsllbtPNJHd2/l3ChEBOPNEbFTnAXHvXsH7Hn7FjJ/wAEoY/hvritY658SvDt3e64zjEsN5qSPIwbIzujLqpPZoyeO312XLBt2W3Ag8459eO/J65oLbuo4xyPXr1+vX659cUAfm7+x9+3zqH/AAT6+Cen/Bn42fD34iWfiTwCrabpl/o2iSalZa5ag/uTHImQHKnBBx0zntXRfsQfCvx18bfj58Zv2lPGnhi+8Gr4x0F9C8K6JfqFvFsY9reZIo+6ztGnBHtzX37JEsq/Mufm35z0bJwR9M4x7U4D5eu0ldhKgdM59PWgD47/AOCF/hPUvBv/AAT50mx1bTdQ0u7XW9Xb7PeW7QzrEb2bDMGAPO7gjrkV5H4b8W+IP+CSP7ZPxWufEfg3xR4k+Enxb1P/AISGx1nQbFr6TS71ixmSaNQWCtkDcDxjoa/SDGQw2r8x7Z/x/HjHNNeBZVKuu+NgQVY/ez60AflH+1L+0v4r/bm/bZ/Zn1vwv8OPHWm/C/wr4+sXOq6npckMl5cfaIjLIYsbo40RT8z8Hn05/WBlwW6bc4z0yevGeowetNxg5/iwACexHfjHcA/n68HTt8vYZzt+maACiiigAooooAKKKKACiiigAooooAKG+43+6f5UUUATW3/IP/4BRD/yDm+v9aKKAIaKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD//Z",
"filename":"filename.jpg"
}
```

**Comment by SagarKhurana** [comment]
@puneet739  I am still unable to send the request.. even after have the image encoded to Base64. 
i am still getting 415 error. 
Can you check anything in this? 
{
"base64":"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsK                                                             CwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQU                                                             FBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCACgAFoDASIA                                                             AhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQA                                                             AAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3                                                             ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWm                                                             p6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEA                                                             AwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSEx                                                             BhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElK                                                             U1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3                                                             uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD87hJ2                                                             wMe1MYAjkfpUZ34xtqJ94+8pFeKkfStk4AbPH+fzrS0hjG0fGAZG/wDQRWKGPv6VuaQC0Vt8hwGZ                                                             s+nGP61vSVmcOJd4HSaOhn13RoV5330Ax7bxXvOg6XcT2ts8IV4zO/mM+c+WdzAjGOc7R+NeO/Du                                                             wbU/Hvh+3XqbgyAkZ+6pbP6V9T6F4fktbV1mSNH3bmWMkquQMgE8kDpnjPXA6D6PB6QbPlcXrNam                                                             f8M/D4j8SeZ9j8lhCoM52/vsKQOhzxnHOK9Og86U4NsqjftyJlPHy8n8+nt71jfDXToZPEeotHHM                                                             rxx7H8zO0kN1Azx19uMdsV29lpKRFSUiDBQP+PXyz+f4dvaliPjIo35TDeKQKxNs5I6YKndx25qh                                                             cSBGUfZbg7gT8secYGef89vpnaigtmMGBbkTb8Mtu6bsZHfp9T17dazLS1t7iHTjusmHzpxvPfGF                                                             DfTnd+Fc5uihIV3mMwTKckZ8s46kZ4+lVi8KkgrJkcf6l/8ACti4tkjkncGA7S5O26ZccnOR0HPW                                                             sKS0dZHGTwSP+Qqf8KQH5+7V2nhfrmoXRSpxjH1qZrbIOD+tRta98/rXzSZ920+xB5ft+ta+k4+z                                                             qDgEE/zrM+zk5wc/jWjpg8uBRzwT/M11UdzzcVpFHqfwIt/tHxW8Orgfen/9ESV9jzaUIrWYhedh                                                             P6V8k/s1WhvPjBoWBkRJO5z2HkuP5mvt2Ox8+0kBX7xZP1Ir6zBr92fG4x/vDP8Ah9YXg1nUzdQr                                                             FCoIgZW+8mV5PJ5yD6cY4roooy32RxjbIZS3+lq44zjr16dumPQU/wCHPhuzsm1lrCA2zTzPLKz5                                                             cNK2MsMnp8o4HHbg5rqoNAeAjLRHaDtKwBSMlu/4j8vc1zYjSo0FDWFzhDpM7PBh7vEcrgn7QhyD                                                             u+8McjIHHUH6Go1sZrVY1b7ZIM4+cxt1Y9SPw/DHfNdlc6DL5bYS0ZwSy7oCADnr1Pvz71m3egSN                                                             KCI4Cg2HJ3ZyGycDt6j361znQcXfwzPDeqFuGIK7AbdD/Fn5c8Nj36cd6gOkeaS/lJ83PzQLn8cn                                                             NdGfDMiRThra3LSxhW2yyDcQCBk8469eo96kg0dUhjVoE3BQD8xb9SMn6mgZ+UwhkBI3H8zUUkUv                                                             PUfiaeucnp+dPXODkDP1r5xaH3TRWWGQr3P4mtawXbGgz0rOY4BHGP8AerRsTmNPcCumjqzzcVZR                                                             R9B/siWiTfE6edz8tppksx4yQNyLnj6mvty2sxFb5I6uf1Y18i/saeG72+1/xRqCWdzNp8GlC3uJ                                                             4omZIjLKu0EjoSEbAyCdpxX2xPZfuFAH8aH/AMeFfW4XSnY+Kxf8RlvwrbLCl2zkKqhSWbgAc5rZ                                                             3W8jBUljdmUSBVYElex+nvUGk2hFje4BG8BMhN/qPu9+tWLS2CFZX3ExxCL/AI9NjdvTt7Dj8q5K                                                             1nNmlFe6QNEjgFWVgRkEHqPX9apz2g5q1MkcSI5a3ZoyI2c2rA88YAzkZ4/T61RuVSSa7hHk77cf                                                             IgLjbmM9QOv4fzrnNylc2mARWebUZPy/pT7uzt/sc2PsGBL5y75nRQTtAJPY9cEe3vVg6JbMSTDE                                                             xPJIXrSGfjcbtiew/GnfaSB2/ClW2XGep96XyVU54/KvnFY+8cZEf2licZHp0rf0KDzWhVu+O2TW                                                             PHGgBOBmtfSr1rSRChKkY5HGK66Gt7HlYxNJXP0m/YF+H0ep+Afidm0upZXtbERnzxCchp2OFPBP                                                             yjlunQYzke4rZqYY84Pyg8V8q/sEeN9Xtbfxj9nliSNjYxSGWFJSdzSAcvkjjPT174r6wjRkjgQ5                                                             OcKfyP8AhX0+Gi4ptnxeJmm0uqNDTbBv7LmkwAgbdlnKDjH8QqG9jMdhcqivlAD8t1t7/wB4nK8f                                                             /WrQs1lk0yWFJPKJb5WK7tvTsabPpTSvdEvGRMFGGhU4wCOf73Y81z1H77NafwowNRE8/wDaMUaT                                                             cKjI8N2itnrgZ+70PXg5qRrKcXV0+65MbxYAMiYDf7I7H8cVqDSFXfuW2bcoUgW4wRljjr056f40                                                             lzascsoiLY25ZT0yP6du5rE2TOevIplKxh7vLEgNsQgYz144zWI9xdh2wl2Oen2IH9c81vXOk3JF                                                             uEitj5R6sz8Asc4GfTHB68jjisqbwvumkK2lltLEjLyDuew4oGrH5AjQ7tlJ+zyf98N/hQ2h3QH/                                                             AB7z5/65GvfY9O3Ass9s49lP+NONi6qPmi5/iANfnqx77H608HHufPj6NdKpza3HHP8Aqzj+VFoP                                                             3gz1PavcNbRbbSL5mdQywuflX/ZPtXiNtt80Z+le9l1d1+ZtWsfM5tRVLlSfc+2P2DJlhtvFql1U                                                             Pc6cuWJGT++OOAfT2+or7X8o/u/Zs/oa+Pv2B4lh8LeNbrKxNJJbxqzEAEqkh78fxV9KNrHiOBpR                                                             9laZVyFKqDnAGM4Hc5+mK+2ppuJ+eV2lNnoNrcLbwxK2SZXKjA6HBPP/AHyasyOCteaDxTr7IVbS                                                             JkKZIfZ9489Pm7+4HUe+IT4v1wMomspoB3LgAD8m9v1rOWHlJt3FGvFK1j0h3FV2Oc81yS+IJsxg                                                             ySO7IrERruAyQPXt1PsKf/b0rymNWlzkqC0Dgcc9SMY9+9Y+xfc3VRG/N35FViy5PJ/OuYvPE8tq                                                             ZvNkCiPrhSSflLcALk8A1mDxzAeftsA9mYgj6grxUezZpzpdD88vCV2j/wChX6xtPHgI6fMsoOSC                                                             pP3gQCQevysDyuW0vF+r2vhqxiK2az3tw4ht4NuN7+vGSQPYE5IGOa4bxdOfBXjeWHTt0JtNknkN                                                             yiEkSbV5ztPHHuwrsPBOrz/ErxTb6wU2HS7XYIGbKpK7sNw45yqnqPT0r83q0EksTb3LX7en3n6z                                                             DEO8sPf3k7L06/cYWseEdbvNCv7/AFjUbm28uCSVLGxhESDCkgO3JIwMFcn/AHjXlsD+W2fSvqXx                                                             vb36eEdaMhG0WU2fl6/I3t9a+UWkKNnPTvXrZPWdSMm+j6Hh5xTUJRt2Prb9kjxzqGi6LeWiSMLC                                                             51DDosSH5gigEsw4XB/zmvoub4qyW/i6Wyv5LeeKGRkeRIYmZWCk5WQKM8n07mvzh0P4j6n4dsFt                                                            LN2hjEhlzFcTxZY45ISRQTwO1aFt",
"filename":"filename.jpg"
}

**Comment by puneet739** [comment]
@SagarKhurana @laherajmani  This is under development.. The Activity UI need to be beautified

**Comment by SagarKhurana** [comment]
@puneet739 please check once I commit the code... and let us know, how we can improve the UI.

**Comment by puneet739** [comment]
@SagarKhurana 
Kindly push the code.. Will check it

**Comment by puneet739** [comment]
@SagarKhurana  This one is still not working... Kindly check once.

**Comment by SagarKhurana** [comment]
@puneet739  hi.. change password and upload image working now!

**Comment by puneet739** [comment]
@SagarKhurana User image upload not working

**Comment by puneet739** [comment]
@SagarKhurana Kindly check. I have just checkout recent code and able to do image upload.
But as discussed with you, we need a crop feature here to upload only selected file size, similar to watsapp image in which we pass only circled image. 

Kindly implement the same, also while uploading the file after successfull upload trigger the save details click/call automatically so that user need not save the tab again.

**Comment by puneet739** [comment]
Closing this as it is duplicate for 
https://github.com/puneet739/SocietyFocus-Android/issues/3
