### ISSUE TITLE
Add admom in layout design for ad generation. → Add this via admob. 

### ISSUE THREAD

**Issue by puneet739** [puneet739/SocietyFocus-Android#5]
Add admom in layout design for ad generation. → Add this via admob.

**Comment by puneet739** [comment]
@laherajmani  this is not completed yet.

**Comment by SagarKhurana** [comment]
@puneet739 its done ... on all the activites except those who involves Collapsible Action Bar.

**Comment by puneet739** [comment]
@SagarKhurana  Fixed and clossing... Will update in case of changing the admom details.
