### ISSUE TITLE
Complaints View

### ISSUE THREAD

**Issue by puneet739** [puneet739/SocietyFocus-Android#9]
Complaints view page should have option to display comments. 

1) Options to add comment. 
2) View current comments. --> added by --> added date.

**Comment by SagarKhurana** [comment]
@puneet739  on add comment click which api we will use to upload the comment to the server for the particular complaint. 

We would be adding add comment and view comments... is there any other feature needs to be included?

**Comment by puneet739** [comment]
API for adding comment 

Get Request. 
http://societyfocus.com/service/v1/comment/add/complaint_{Complaint_ID}/{MESSAGE}

Access Token will be in header.

**Comment by puneet739** [comment]
For Example 
http://societyfocus.com/service/v1/comment/add/complaint_5/test-comment

**Comment by puneet739** [comment]
Complaint Response will be 

``` json
{
  "body": {
    "complaint": {
      "complaintid": 5,
      "societyId": 0,
      "title": "gyser",
      "description": "not wrkng",
      "email": "meghaz",
      "user": {
        "userid": 7,
        "firstname": "Megha",
        "lastname": "Bhatia",
        "email": "Meghab89@gmail.com",
        "contact_no": "9711616134",
        "status": 1,
        "address": "1396",
        "keyValuePairs": {}
      },
      "status": 0,
      "creationdate": "2016-02-19T10:46:04 +0000"
    },
    "comments": [
      {
        "commentid": 16,
        "user": {
          "userid": 1,
          "firstname": "Puneet",
          "lastname": "Solank",
          "occupation": "Engineer",
          "email": "puneet@gmail.com",
          "contact_no": "9711616135",
          "profile_pic": "https://media.licdn.com/mpr/mpr/shrinknp_200_200/p/3/000/07c/170/0e906e6.jpg",
          "description": "software engineer",
          "address": "Super Admin lp",
          "keyValuePairs": {}
        },
        "comment": "test comment",
        "linkId": "complaint_5",
        "creationdate": "2016-07-29T13:20:00 +0000",
        "modifieddate": "2016-07-29T13:20:00 +0000"
      },
      {
        "commentid": 17,
        "user": {
          "userid": 1,
          "firstname": "Puneet",
          "lastname": "Solank",
          "occupation": "Engineer",
          "email": "puneet@gmail.com",
          "contact_no": "9711616135",
          "profile_pic": "https://media.licdn.com/mpr/mpr/shrinknp_200_200/p/3/000/07c/170/0e906e6.jpg",
          "description": "software engineer",
          "address": "Super Admin lp",
          "keyValuePairs": {}
        },
        "comment": "test comment2",
        "linkId": "complaint_5",
        "creationdate": "2016-07-29T13:20:09 +0000",
        "modifieddate": "2016-07-29T13:20:09 +0000"
      }
    ]
  },
  "status": 0
}
```

**Comment by SagarKhurana** [comment]
@puneet739  
if we will use this api, it is only sending the comment as appended text.
how we are sending user's object like which user have commented on it. 
are you handling it at backend using accesstoken?

**Comment by puneet739** [comment]
@SagarKhurana  Yes, This is taken care of in backend.. The user who have logged in, the comments will be pushed via his details.

**Comment by SagarKhurana** [comment]
@puneet739  successful to add comments to the server...  sending u pull request.

**Comment by SagarKhurana** [comment]
completed

**Comment by puneet739** [comment]
@SagarKhurana @laherajmani  kindly remove that view comments box and make add comment col-md-12 so that it takes complete width.. After that we can close this issue.

**Comment by SagarKhurana** [comment]
@puneet739  its done kindly check.

**Comment by puneet739** [comment]
@SagarKhurana  kindly commit and push the code..

**Comment by puneet739** [comment]
Fixed and closing
